/*
  2014 Mahyar Koshkouei
  
  Minesweeper
*/

#include <Adafruit_GFX.h>
#include <Adafruit_PCD8544.h>

// Below are hte usual pins for connecting to a Nokia 5110 LCD
// pin 7 - Serial clock out (SCLK)
// pin 6 - Serial data out (DIN)
// pin 5 - Data/Command select (D/C)
// pin 4 - LCD chip select (CS)
// pin 3 - LCD reset (RST)

Adafruit_PCD8544 display = Adafruit_PCD8544(13, 11, 7, 12, 10);
// My Nokia 5110 LCD requires different pins than the usual because it's a wierd one.

// Below are variable for use with a Funduino Joystick Shield V1.A, although most of the buttons aren't needed for this game.
byte up_button = 2;
byte down_button = 4;
byte left_button = 5;
byte right_button = 3;
byte start_button = 6;
byte select_button = 7;
byte analog_button = 8;
byte x_axis = A0;
byte y_axis = A1;
byte buttons[] = {up_button, down_button, left_button, right_button, start_button, select_button, analog_button};

//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------
// 7x7
const unsigned char PROGMEM box [] = {
0xFE, 0x82, 0x82, 0x82, 0x82, 0x82, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

void setup() {
  //Initialise the Joystick shield
  for (int i; i < 7; i++)
  {
   pinMode(buttons[i], INPUT);
   digitalWrite(buttons[i], HIGH);
  }
  
  display.begin();
  // init done

  // you can change the contrast around to adapt the display
  // for the best viewing!
  display.setContrast(50);
  delay(500);
  display.clearDisplay();   // clears the screen and buffer
  
  for (int y = 0; y < 42; y = y + 6) {
    for (int x = 0; x < 78; x = x + 6) { 
      display.drawBitmap(x, y, box, 7, 7, BLACK);
    }
  }
  display.display();
}

void loop() {
  // put your main code here, to run repeatedly:

}
